// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef SpaceWrapper_hpp__pyplusplus_wrapper
#define SpaceWrapper_hpp__pyplusplus_wrapper

void register_SpaceWrapper_class();

#endif//SpaceWrapper_hpp__pyplusplus_wrapper
