#!/bin/bash

while (( "$#" )); do
  case "$1" in
    -n|--name)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        NAME=$2
        shift 2
      else
        echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -e|--email)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        EMAIL=$2
        shift 2
      else
	echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -p|--password)
      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
        PASSWORD=$2
        shift 2
      else
	echo "Error: Argument for $1 is missing" >&2
        exit 1
      fi
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
  esac
done

if [[ -z "${NAME+set}" ]]; then
    echo "USAGE: push_wrappers --name \"{NAME}\" --email {EMAIL}"
    exit 1
fi

if [[ -z "${EMAIL+set}" ]]; then
    echo "USAGE: push_wrappers --name \"{NAME}\" --email {EMAIL}"
    exit 1
fi

cd $HOME/Sire
git config --global user.name $NAME
git config --global user.email $EMAIL
git add .
git commit -a -m "Updated the python wrappers"
git push
