// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef vector_less__double__greater__hpp__pyplusplus_wrapper
#define vector_less__double__greater__hpp__pyplusplus_wrapper

void register_vector_less__double__greater__class();

#endif//vector_less__double__greater__hpp__pyplusplus_wrapper
