// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef TriclinicBox_hpp__pyplusplus_wrapper
#define TriclinicBox_hpp__pyplusplus_wrapper

void register_TriclinicBox_class();

#endif//TriclinicBox_hpp__pyplusplus_wrapper
