// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef AtomEnergies_hpp__pyplusplus_wrapper
#define AtomEnergies_hpp__pyplusplus_wrapper

void register_AtomEnergies_class();

#endif//AtomEnergies_hpp__pyplusplus_wrapper
