// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef MoleculeView_hpp__pyplusplus_wrapper
#define MoleculeView_hpp__pyplusplus_wrapper

void register_MoleculeView_class();

#endif//MoleculeView_hpp__pyplusplus_wrapper
