// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef Perturbation_hpp__pyplusplus_wrapper
#define Perturbation_hpp__pyplusplus_wrapper

void register_Perturbation_class();

#endif//Perturbation_hpp__pyplusplus_wrapper
