// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef PMF_hpp__pyplusplus_wrapper
#define PMF_hpp__pyplusplus_wrapper

void register_PMF_class();

#endif//PMF_hpp__pyplusplus_wrapper
