#ifndef ACTIVE_HEADERS_H
#define ACTIVE_HEADERS_H

#ifdef GCCXML_PARSE

#include "amberparams.h"
#include "anglerestraint.h"
#include "atomfunctions.h"
#include "atomljs.h"
#include "clj14group.h"
#include "cljatoms.h"
#include "cljboxes.h"
#include "cljcalculator.h"
#include "cljcomponent.h"
#include "cljdelta.h"
#include "cljextractor.h"
#include "cljfunction.h"
#include "cljgrid.h"
#include "cljgroup.h"
#include "cljnbpairs.h"
#include "cljparam.h"
#include "cljpotential.h"
#include "cljprobe.h"
#include "cljrffunction.h"
#include "cljshiftfunction.h"
#include "cljworkspace.h"
#include "coulombpotential.h"
#include "dihedralrestraint.h"
#include "distancerestraint.h"
#include "fouratomfunctions.h"
#include "gridff.h"
#include "gridff2.h"
#include "intercljff.h"
#include "intercoulombff.h"
#include "interff.h"
#include "intergroupff.h"
#include "interljff.h"
#include "internalcomponent.h"
#include "internalff.h"
#include "internalparameters.h"
#include "internalperturbation.h"
#include "intersoftcljff.h"
#include "intracljff.h"
#include "intracoulombff.h"
#include "intraff.h"
#include "intragroupff.h"
#include "intraljff.h"
#include "intrasoftcljff.h"
#include "ljpair.h"
#include "ljparameter.h"
#include "ljperturbation.h"
#include "ljpotential.h"
#include "mol2params.h"
#include "multicljcomponent.h"
#include "pdbparams.h"
#include "restraint.h"
#include "restraintcomponent.h"
#include "restraintff.h"
#include "softcljcomponent.h"
#include "switchingfunction.h"
#include "testff.h"
#include "threeatomfunctions.h"
#include "twoatomfunctions.h"

#endif

#endif
