// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef AmberAngle_hpp__pyplusplus_wrapper
#define AmberAngle_hpp__pyplusplus_wrapper

void register_AmberAngle_class();

#endif//AmberAngle_hpp__pyplusplus_wrapper
