// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef AngleComponent_hpp__pyplusplus_wrapper
#define AngleComponent_hpp__pyplusplus_wrapper

void register_AngleComponent_class();

#endif//AngleComponent_hpp__pyplusplus_wrapper
