// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef CLJPotentialInterface_InterSoftCLJPotential__hpp__pyplusplus_wrapper
#define CLJPotentialInterface_InterSoftCLJPotential__hpp__pyplusplus_wrapper

void register_CLJPotentialInterface_InterSoftCLJPotential__class();

#endif//CLJPotentialInterface_InterSoftCLJPotential__hpp__pyplusplus_wrapper
