// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef InternalPerturbation_hpp__pyplusplus_wrapper
#define InternalPerturbation_hpp__pyplusplus_wrapper

void register_InternalPerturbation_class();

#endif//InternalPerturbation_hpp__pyplusplus_wrapper
