// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#include "boost/python.hpp"
#include "Mover_Improper_.pypp.hpp"

namespace bp = boost::python;

#include "SireBase/errors.h"

#include "SireCAS/expression.h"

#include "SireCAS/symbol.h"

#include "SireCAS/values.h"

#include "SireMaths/torsion.h"

#include "SireMol/errors.h"

#include "SireMol/molecule.h"

#include "SireMol/mover.hpp"

#include "SireMol/selector.hpp"

#include "SireStream/datastream.h"

#include "SireStream/shareddatastream.h"

#include "SireUnits/units.h"

#include "fouratomfunctions.h"

#include "improper.h"

#include "selectorimproper.h"

#include <QDebug>

#include "improper.h"

#include "SireMaths/align.h"

#include "SireMaths/axisset.h"

#include "SireMaths/matrix.h"

#include "SireMaths/quaternion.h"

#include "SireMaths/rotate.h"

#include "SireMaths/vectorproperty.h"

#include "SireMol/errors.h"

#include "SireUnits/units.h"

#include "SireVol/coordgroup.h"

#include "SireVol/space.h"

#include "angleid.h"

#include "atomcoords.h"

#include "atommatcher.h"

#include "atommatchers.h"

#include "bondid.h"

#include "connectivity.h"

#include "dihedralid.h"

#include "improperid.h"

#include "mover.h"

#include "tostring.h"

#include "weightfunction.h"

#include "mover.h"

SireMol::Mover<SireMM::Improper> __copy__(const SireMol::Mover<SireMM::Improper> &other){ return SireMol::Mover<SireMM::Improper>(other); }

#include "Helpers/str.hpp"

#include "Helpers/release_gil_policy.hpp"

#include "Helpers/len.hpp"

void register_Mover_Improper__class(){

    { //::SireMol::Mover< SireMM::Improper >
        typedef bp::class_< SireMol::Mover< SireMM::Improper >, bp::bases< SireMol::MoverBase, SireMM::Improper, SireMol::MoleculeView, SireBase::Property > > Mover_Improper__exposer_t;
        Mover_Improper__exposer_t Mover_Improper__exposer = Mover_Improper__exposer_t( "Mover_Improper_", "", bp::init< >("") );
        bp::scope Mover_Improper__scope( Mover_Improper__exposer );
        Mover_Improper__exposer.def( bp::init< SireMM::Improper const & >(( bp::arg("view") ), "") );
        Mover_Improper__exposer.def( bp::init< SireMM::Improper const &, SireMol::AtomSelection const & >(( bp::arg("view"), bp::arg("movable_atoms") ), "") );
        Mover_Improper__exposer.def( bp::init< SireMol::Mover< SireMM::Improper > const & >(( bp::arg("other") ), "") );
        { //::SireMol::Mover< SireMM::Improper >::align
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*align_function_type)( ::SireMol::MoleculeView const &,::SireBase::PropertyMap const & ) ;
            align_function_type align_function_value( &::SireMol::Mover< SireMM::Improper >::align );
            
            Mover_Improper__exposer.def( 
                "align"
                , align_function_value
                , ( bp::arg("other"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::align
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*align_function_type)( ::SireMol::MoleculeView const &,::SireBase::PropertyMap const &,::SireBase::PropertyMap const & ) ;
            align_function_type align_function_value( &::SireMol::Mover< SireMM::Improper >::align );
            
            Mover_Improper__exposer.def( 
                "align"
                , align_function_value
                , ( bp::arg("other"), bp::arg("map0"), bp::arg("map1") )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::align
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*align_function_type)( ::SireMol::MoleculeView const &,::SireMol::AtomMatcher const &,::SireBase::PropertyMap const & ) ;
            align_function_type align_function_value( &::SireMol::Mover< SireMM::Improper >::align );
            
            Mover_Improper__exposer.def( 
                "align"
                , align_function_value
                , ( bp::arg("other"), bp::arg("matcher"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::align
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*align_function_type)( ::SireMol::MoleculeView const &,::SireMol::AtomMatcher const &,::SireBase::PropertyMap const &,::SireBase::PropertyMap const & ) ;
            align_function_type align_function_value( &::SireMol::Mover< SireMM::Improper >::align );
            
            Mover_Improper__exposer.def( 
                "align"
                , align_function_value
                , ( bp::arg("other"), bp::arg("matcher"), bp::arg("map0"), bp::arg("map1") )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::change
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*change_function_type)( ::SireMol::BondID const &,::SireUnits::Dimension::Length,::SireBase::PropertyMap const & ) ;
            change_function_type change_function_value( &::SireMol::Mover< SireMM::Improper >::change );
            
            Mover_Improper__exposer.def( 
                "change"
                , change_function_value
                , ( bp::arg("bond"), bp::arg("delta"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::change
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*change_function_type)( ::SireMol::AngleID const &,::SireUnits::Dimension::Angle,::SireBase::PropertyMap const & ) ;
            change_function_type change_function_value( &::SireMol::Mover< SireMM::Improper >::change );
            
            Mover_Improper__exposer.def( 
                "change"
                , change_function_value
                , ( bp::arg("angle"), bp::arg("delta"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::change
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*change_function_type)( ::SireMol::DihedralID const &,::SireUnits::Dimension::Angle,::SireBase::PropertyMap const & ) ;
            change_function_type change_function_value( &::SireMol::Mover< SireMM::Improper >::change );
            
            Mover_Improper__exposer.def( 
                "change"
                , change_function_value
                , ( bp::arg("dihedral"), bp::arg("delta"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::change
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*change_function_type)( ::SireMol::BondID const &,::SireUnits::Dimension::Angle,::SireBase::PropertyMap const & ) ;
            change_function_type change_function_value( &::SireMol::Mover< SireMM::Improper >::change );
            
            Mover_Improper__exposer.def( 
                "change"
                , change_function_value
                , ( bp::arg("bond"), bp::arg("delta"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::change
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*change_function_type)( ::SireMol::ImproperID const &,::SireUnits::Dimension::Angle,::SireBase::PropertyMap const & ) ;
            change_function_type change_function_value( &::SireMol::Mover< SireMM::Improper >::change );
            
            Mover_Improper__exposer.def( 
                "change"
                , change_function_value
                , ( bp::arg("improper"), bp::arg("delta"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::changeFrame
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*changeFrame_function_type)( ::SireMaths::AxisSet const &,::SireMaths::AxisSet const &,::SireBase::PropertyMap const & ) ;
            changeFrame_function_type changeFrame_function_value( &::SireMol::Mover< SireMM::Improper >::changeFrame );
            
            Mover_Improper__exposer.def( 
                "changeFrame"
                , changeFrame_function_value
                , ( bp::arg("from_frame"), bp::arg("to_frame"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::commit
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMM::Improper ( ::SireMol::Mover< SireMM::Improper >::*commit_function_type)(  ) const;
            commit_function_type commit_function_value( &::SireMol::Mover< SireMM::Improper >::commit );
            
            Mover_Improper__exposer.def( 
                "commit"
                , commit_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::mapInto
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*mapInto_function_type)( ::SireMaths::AxisSet const &,::SireBase::PropertyMap const & ) ;
            mapInto_function_type mapInto_function_value( &::SireMol::Mover< SireMM::Improper >::mapInto );
            
            Mover_Improper__exposer.def( 
                "mapInto"
                , mapInto_function_value
                , ( bp::arg("axes"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::operator=
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*assign_function_type)( ::SireMol::Mover< SireMM::Improper > const & ) ;
            assign_function_type assign_function_value( &::SireMol::Mover< SireMM::Improper >::operator= );
            
            Mover_Improper__exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::operator=
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*assign_function_type)( ::SireMM::Improper const & ) ;
            assign_function_type assign_function_value( &::SireMol::Mover< SireMM::Improper >::operator= );
            
            Mover_Improper__exposer.def( 
                "assign"
                , assign_function_value
                , ( bp::arg("other") )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::rotate
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*rotate_function_type)( ::SireMaths::Quaternion const &,::SireMaths::Vector const &,::SireBase::PropertyMap const & ) ;
            rotate_function_type rotate_function_value( &::SireMol::Mover< SireMM::Improper >::rotate );
            
            Mover_Improper__exposer.def( 
                "rotate"
                , rotate_function_value
                , ( bp::arg("quat"), bp::arg("point"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::rotate
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*rotate_function_type)( ::SireMaths::Matrix const &,::SireMaths::Vector const &,::SireBase::PropertyMap const & ) ;
            rotate_function_type rotate_function_value( &::SireMol::Mover< SireMM::Improper >::rotate );
            
            Mover_Improper__exposer.def( 
                "rotate"
                , rotate_function_value
                , ( bp::arg("rotmat"), bp::arg("point"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::set
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*set_function_type)( ::SireMol::BondID const &,::SireUnits::Dimension::Length,::SireBase::PropertyMap const & ) ;
            set_function_type set_function_value( &::SireMol::Mover< SireMM::Improper >::set );
            
            Mover_Improper__exposer.def( 
                "set"
                , set_function_value
                , ( bp::arg("bond"), bp::arg("value"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::set
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*set_function_type)( ::SireMol::AngleID const &,::SireUnits::Dimension::Angle,::SireBase::PropertyMap const & ) ;
            set_function_type set_function_value( &::SireMol::Mover< SireMM::Improper >::set );
            
            Mover_Improper__exposer.def( 
                "set"
                , set_function_value
                , ( bp::arg("angle"), bp::arg("value"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::set
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*set_function_type)( ::SireMol::DihedralID const &,::SireUnits::Dimension::Angle,::SireBase::PropertyMap const & ) ;
            set_function_type set_function_value( &::SireMol::Mover< SireMM::Improper >::set );
            
            Mover_Improper__exposer.def( 
                "set"
                , set_function_value
                , ( bp::arg("dihedral"), bp::arg("value"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::set
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*set_function_type)( ::SireMol::ImproperID const &,::SireUnits::Dimension::Angle,::SireBase::PropertyMap const & ) ;
            set_function_type set_function_value( &::SireMol::Mover< SireMM::Improper >::set );
            
            Mover_Improper__exposer.def( 
                "set"
                , set_function_value
                , ( bp::arg("improper"), bp::arg("value"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::setAll
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*setAll_function_type)( ::SireMol::DihedralID const &,::SireUnits::Dimension::Angle,::SireBase::PropertyMap const & ) ;
            setAll_function_type setAll_function_value( &::SireMol::Mover< SireMM::Improper >::setAll );
            
            Mover_Improper__exposer.def( 
                "setAll"
                , setAll_function_value
                , ( bp::arg("dihedral"), bp::arg("value"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::toString
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::QString ( ::SireMol::Mover< SireMM::Improper >::*toString_function_type)(  ) const;
            toString_function_type toString_function_value( &::SireMol::Mover< SireMM::Improper >::toString );
            
            Mover_Improper__exposer.def( 
                "toString"
                , toString_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::transform
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*transform_function_type)( ::SireMaths::Transform const &,::SireBase::PropertyMap const & ) ;
            transform_function_type transform_function_value( &::SireMol::Mover< SireMM::Improper >::transform );
            
            Mover_Improper__exposer.def( 
                "transform"
                , transform_function_value
                , ( bp::arg("transform"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::translate
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef ::SireMol::Mover< SireMM::Improper > & ( ::SireMol::Mover< SireMM::Improper >::*translate_function_type)( ::SireMaths::Vector const &,::SireBase::PropertyMap const & ) ;
            translate_function_type translate_function_value( &::SireMol::Mover< SireMM::Improper >::translate );
            
            Mover_Improper__exposer.def( 
                "translate"
                , translate_function_value
                , ( bp::arg("delta"), bp::arg("map")=SireBase::PropertyMap() )
                , bp::return_self< >()
                , "" );
        
        }
        { //::SireMol::Mover< SireMM::Improper >::typeName
        
            typedef SireMol::Mover< SireMM::Improper > exported_class_t;
            typedef char const * ( *typeName_function_type )(  );
            typeName_function_type typeName_function_value( &::SireMol::Mover< SireMM::Improper >::typeName );
            
            Mover_Improper__exposer.def( 
                "typeName"
                , typeName_function_value
                , bp::release_gil_policy()
                , "" );
        
        }
        Mover_Improper__exposer.staticmethod( "typeName" );
        Mover_Improper__exposer.def( "__copy__", &__copy__);
        Mover_Improper__exposer.def( "__deepcopy__", &__copy__);
        Mover_Improper__exposer.def( "clone", &__copy__);
        Mover_Improper__exposer.def( "__str__", &__str__< ::SireMol::Mover<SireMM::Improper> > );
        Mover_Improper__exposer.def( "__repr__", &__str__< ::SireMol::Mover<SireMM::Improper> > );
        Mover_Improper__exposer.def( "__len__", &__len_size< ::SireMol::Mover<SireMM::Improper> > );
    }

}
