// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef InternalFlipMove_hpp__pyplusplus_wrapper
#define InternalFlipMove_hpp__pyplusplus_wrapper

void register_InternalFlipMove_class();

#endif//InternalFlipMove_hpp__pyplusplus_wrapper
