// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef InternalMove_hpp__pyplusplus_wrapper
#define InternalMove_hpp__pyplusplus_wrapper

void register_InternalMove_class();

#endif//InternalMove_hpp__pyplusplus_wrapper
