// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef ArcCsch_hpp__pyplusplus_wrapper
#define ArcCsch_hpp__pyplusplus_wrapper

void register_ArcCsch_class();

#endif//ArcCsch_hpp__pyplusplus_wrapper
