// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef ArcSech_hpp__pyplusplus_wrapper
#define ArcSech_hpp__pyplusplus_wrapper

void register_ArcSech_class();

#endif//ArcSech_hpp__pyplusplus_wrapper
