// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef Identities_hpp__pyplusplus_wrapper
#define Identities_hpp__pyplusplus_wrapper

void register_Identities_class();

#endif//Identities_hpp__pyplusplus_wrapper
