//WARNING - AUTOGENERATED FILE - CONTENTS WILL BE OVERWRITTEN!
#include <Python.h>

#include "SireCAS_registrars.h"

#include "minmax.h"
#include "exp.h"
#include "functionsignature.h"
#include "constant.h"
#include "complexvalues.h"
#include "values.h"
#include "abs.h"
#include "powerconstant.h"
#include "invtrigfuncs.h"
#include "invhyperbolicfuncs.h"
#include "function.h"
#include "i.h"
#include "hyperbolicfuncs.h"
#include "expression.h"
#include "power.h"
#include "trigfuncs.h"
#include "integrationconstant.h"
#include "product.h"
#include "conditional.h"
#include "identities.h"
#include "sum.h"
#include "symbol.h"
#include "expressionproperty.h"

#include "Helpers/objectregistry.hpp"

void register_SireCAS_objects()
{

    ObjectRegistry::registerConverterFor< SireCAS::Min >();
    ObjectRegistry::registerConverterFor< SireCAS::Max >();
    ObjectRegistry::registerConverterFor< SireCAS::Exp >();
    ObjectRegistry::registerConverterFor< SireCAS::Ln >();
    ObjectRegistry::registerConverterFor< SireCAS::FunctionSignature >();
    ObjectRegistry::registerConverterFor< SireCAS::Constant >();
    ObjectRegistry::registerConverterFor< SireCAS::ComplexValues >();
    ObjectRegistry::registerConverterFor< SireCAS::Values >();
    ObjectRegistry::registerConverterFor< SireCAS::Abs >();
    ObjectRegistry::registerConverterFor< SireCAS::PowerConstant >();
    ObjectRegistry::registerConverterFor< SireCAS::IntegerPower >();
    ObjectRegistry::registerConverterFor< SireCAS::RationalPower >();
    ObjectRegistry::registerConverterFor< SireCAS::RealPower >();
    ObjectRegistry::registerConverterFor< SireCAS::ComplexPower >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcCos >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcSin >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcTan >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcCsc >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcSec >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcCot >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcCosh >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcSinh >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcTanh >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcCsch >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcSech >();
    ObjectRegistry::registerConverterFor< SireCAS::ArcCoth >();
    ObjectRegistry::registerConverterFor< SireCAS::Function >();
    ObjectRegistry::registerConverterFor< SireCAS::I >();
    ObjectRegistry::registerConverterFor< SireCAS::Cosh >();
    ObjectRegistry::registerConverterFor< SireCAS::Sinh >();
    ObjectRegistry::registerConverterFor< SireCAS::Tanh >();
    ObjectRegistry::registerConverterFor< SireCAS::Csch >();
    ObjectRegistry::registerConverterFor< SireCAS::Sech >();
    ObjectRegistry::registerConverterFor< SireCAS::Coth >();
    ObjectRegistry::registerConverterFor< SireCAS::Expression >();
    ObjectRegistry::registerConverterFor< SireCAS::Power >();
    ObjectRegistry::registerConverterFor< SireCAS::Cos >();
    ObjectRegistry::registerConverterFor< SireCAS::Sin >();
    ObjectRegistry::registerConverterFor< SireCAS::Tan >();
    ObjectRegistry::registerConverterFor< SireCAS::Csc >();
    ObjectRegistry::registerConverterFor< SireCAS::Sec >();
    ObjectRegistry::registerConverterFor< SireCAS::Cot >();
    ObjectRegistry::registerConverterFor< SireCAS::IntegrationConstant >();
    ObjectRegistry::registerConverterFor< SireCAS::Product >();
    ObjectRegistry::registerConverterFor< SireCAS::Conditional >();
    ObjectRegistry::registerConverterFor< SireCAS::GreaterThan >();
    ObjectRegistry::registerConverterFor< SireCAS::LessThan >();
    ObjectRegistry::registerConverterFor< SireCAS::GreaterOrEqualThan >();
    ObjectRegistry::registerConverterFor< SireCAS::LessOrEqualThan >();
    ObjectRegistry::registerConverterFor< SireCAS::EqualTo >();
    ObjectRegistry::registerConverterFor< SireCAS::NotEqualTo >();
    ObjectRegistry::registerConverterFor< SireCAS::AlwaysTrue >();
    ObjectRegistry::registerConverterFor< SireCAS::AlwaysFalse >();
    ObjectRegistry::registerConverterFor< SireCAS::Identities >();
    ObjectRegistry::registerConverterFor< SireCAS::Sum >();
    ObjectRegistry::registerConverterFor< SireCAS::Symbol >();
    ObjectRegistry::registerConverterFor< SireCAS::ExpressionProperty >();

}

