// This file has been generated by Py++.

// (C) Christopher Woods, GPL >= 2 License

#ifndef NMatrix_hpp__pyplusplus_wrapper
#define NMatrix_hpp__pyplusplus_wrapper

void register_NMatrix_class();

#endif//NMatrix_hpp__pyplusplus_wrapper
